/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "花花的个人博客",
  "description": "花花的个人博客",
  "base": "/myblog/",
  "headTags": [],
  "pages": [
    {
      "title": "函数",
      "frontmatter": {},
      "regularPath": "/TypeScript_docs/%E5%87%BD%E6%95%B0.html",
      "relativePath": "TypeScript_docs/函数.md",
      "key": "v-58d8fb0e",
      "path": "/TypeScript_docs/%E5%87%BD%E6%95%B0.html",
      "headers": [
        {
          "level": 2,
          "title": "基本示例",
          "slug": "基本示例"
        },
        {
          "level": 2,
          "title": "函数类型",
          "slug": "函数类型"
        },
        {
          "level": 2,
          "title": "为函数定义类型",
          "slug": "为函数定义类型"
        },
        {
          "level": 2,
          "title": "书写完整函数类型",
          "slug": "书写完整函数类型"
        },
        {
          "level": 2,
          "title": "可选参数和默认参数",
          "slug": "可选参数和默认参数"
        },
        {
          "level": 2,
          "title": "剩余参数",
          "slug": "剩余参数"
        },
        {
          "level": 2,
          "title": "函数重载",
          "slug": "函数重载"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/image/banner.png",
        "tagline": "喜欢玩PUBG，不浪敢上心态棒",
        "footer": "wechat 1193375592"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-d2651d16",
      "path": "/"
    },
    {
      "title": "基础类型",
      "frontmatter": {},
      "regularPath": "/TypeScript_docs/%E5%9F%BA%E7%A1%80%E7%B1%BB%E5%9E%8B.html",
      "relativePath": "TypeScript_docs/基础类型.md",
      "key": "v-7865ea98",
      "path": "/TypeScript_docs/%E5%9F%BA%E7%A1%80%E7%B1%BB%E5%9E%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "布尔值",
          "slug": "布尔值"
        },
        {
          "level": 2,
          "title": "数字",
          "slug": "数字"
        },
        {
          "level": 2,
          "title": "字符串",
          "slug": "字符串"
        },
        {
          "level": 2,
          "title": "undefined 和 null",
          "slug": "undefined-和-null"
        },
        {
          "level": 2,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 2,
          "title": "元组 Tuple",
          "slug": "元组-tuple"
        },
        {
          "level": 2,
          "title": "枚举",
          "slug": "枚举"
        },
        {
          "level": 2,
          "title": "any",
          "slug": "any"
        },
        {
          "level": 2,
          "title": "void",
          "slug": "void"
        },
        {
          "level": 2,
          "title": "object",
          "slug": "object"
        },
        {
          "level": 2,
          "title": "联合类型",
          "slug": "联合类型"
        },
        {
          "level": 2,
          "title": "类型断言",
          "slug": "类型断言"
        },
        {
          "level": 2,
          "title": "类型推断",
          "slug": "类型推断"
        }
      ]
    },
    {
      "title": "泛型",
      "frontmatter": {},
      "regularPath": "/TypeScript_docs/%E6%B3%9B%E5%9E%8B.html",
      "relativePath": "TypeScript_docs/泛型.md",
      "key": "v-109e7e7c",
      "path": "/TypeScript_docs/%E6%B3%9B%E5%9E%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "引入",
          "slug": "引入"
        },
        {
          "level": 2,
          "title": "使用函数泛型",
          "slug": "使用函数泛型"
        },
        {
          "level": 2,
          "title": "多个泛型参数的函数",
          "slug": "多个泛型参数的函数"
        },
        {
          "level": 2,
          "title": "泛型接口",
          "slug": "泛型接口"
        },
        {
          "level": 2,
          "title": "泛型类",
          "slug": "泛型类"
        },
        {
          "level": 2,
          "title": "泛型约束",
          "slug": "泛型约束"
        }
      ]
    },
    {
      "title": "接口",
      "frontmatter": {},
      "regularPath": "/TypeScript_docs/%E6%8E%A5%E5%8F%A3.html",
      "relativePath": "TypeScript_docs/接口.md",
      "key": "v-7806a9d2",
      "path": "/TypeScript_docs/%E6%8E%A5%E5%8F%A3.html",
      "headers": [
        {
          "level": 2,
          "title": "接口初探",
          "slug": "接口初探"
        },
        {
          "level": 2,
          "title": "可选属性",
          "slug": "可选属性"
        },
        {
          "level": 2,
          "title": "只读属性",
          "slug": "只读属性"
        },
        {
          "level": 2,
          "title": "readonly vs const",
          "slug": "readonly-vs-const"
        },
        {
          "level": 2,
          "title": "函数类型",
          "slug": "函数类型"
        },
        {
          "level": 2,
          "title": "类类型",
          "slug": "类类型"
        },
        {
          "level": 2,
          "title": "类实现接口",
          "slug": "类实现接口"
        },
        {
          "level": 2,
          "title": "一个类可以实现多个接口",
          "slug": "一个类可以实现多个接口"
        },
        {
          "level": 2,
          "title": "接口继承接口",
          "slug": "接口继承接口"
        }
      ]
    },
    {
      "title": "类",
      "frontmatter": {},
      "regularPath": "/TypeScript_docs/%E7%B1%BB.html",
      "relativePath": "TypeScript_docs/类.md",
      "key": "v-5f8c682c",
      "path": "/TypeScript_docs/%E7%B1%BB.html",
      "headers": [
        {
          "level": 2,
          "title": "基本示例",
          "slug": "基本示例"
        },
        {
          "level": 2,
          "title": "继承",
          "slug": "继承"
        },
        {
          "level": 2,
          "title": "公共，私有与受保护的修饰符",
          "slug": "公共-私有与受保护的修饰符"
        },
        {
          "level": 2,
          "title": "默认为 public",
          "slug": "默认为-public"
        },
        {
          "level": 2,
          "title": "理解 private",
          "slug": "理解-private"
        },
        {
          "level": 2,
          "title": "理解 protected",
          "slug": "理解-protected"
        },
        {
          "level": 2,
          "title": "readonly 修饰符",
          "slug": "readonly-修饰符"
        },
        {
          "level": 2,
          "title": "参数属性",
          "slug": "参数属性"
        },
        {
          "level": 2,
          "title": "存取器",
          "slug": "存取器"
        },
        {
          "level": 2,
          "title": "静态属性",
          "slug": "静态属性"
        },
        {
          "level": 2,
          "title": "抽象类",
          "slug": "抽象类"
        }
      ]
    },
    {
      "title": "Pinia",
      "frontmatter": {},
      "regularPath": "/Vue3_docs/Pinia.html",
      "relativePath": "Vue3_docs/Pinia.md",
      "key": "v-661cd419",
      "path": "/Vue3_docs/Pinia.html",
      "headers": [
        {
          "level": 2,
          "title": "Pinia 基本使用",
          "slug": "pinia-基本使用"
        },
        {
          "level": 2,
          "title": "解构store",
          "slug": "解构store"
        },
        {
          "level": 2,
          "title": "ES传统方式解构(能获取到值，但是不具有响应性)",
          "slug": "es传统方式解构-能获取到值-但是不具有响应性"
        },
        {
          "level": 2,
          "title": "Pinia解构方法：storeToRefs",
          "slug": "pinia解构方法-storetorefs"
        },
        {
          "level": 2,
          "title": "Pinia修改数据状态",
          "slug": "pinia修改数据状态"
        },
        {
          "level": 2,
          "title": "简单数据修改",
          "slug": "简单数据修改"
        },
        {
          "level": 2,
          "title": "多条数据修改",
          "slug": "多条数据修改"
        },
        {
          "level": 2,
          "title": "通过action修改",
          "slug": "通过action修改"
        },
        {
          "level": 2,
          "title": "Pinia中的Getters",
          "slug": "pinia中的getters"
        },
        {
          "level": 2,
          "title": "store之间的相互调用",
          "slug": "store之间的相互调用"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ]
    },
    {
      "title": "Vue3.2",
      "frontmatter": {},
      "regularPath": "/Vue3_docs/Vue3.2.html",
      "relativePath": "Vue3_docs/Vue3.2.md",
      "key": "v-32364cbf",
      "path": "/Vue3_docs/Vue3.2.html",
      "headers": [
        {
          "level": 2,
          "title": "一、文件结构",
          "slug": "一、文件结构"
        },
        {
          "level": 2,
          "title": "二、data",
          "slug": "二、data"
        },
        {
          "level": 2,
          "title": "三、method",
          "slug": "三、method"
        },
        {
          "level": 2,
          "title": "四、computed",
          "slug": "四、computed"
        },
        {
          "level": 2,
          "title": "五、watch",
          "slug": "五、watch"
        },
        {
          "level": 2,
          "title": "六、props父传子",
          "slug": "六、props父传子"
        },
        {
          "level": 3,
          "title": "子组件",
          "slug": "子组件"
        },
        {
          "level": 3,
          "title": "父组件",
          "slug": "父组件"
        },
        {
          "level": 2,
          "title": "七、emit子传父",
          "slug": "七、emit子传父"
        },
        {
          "level": 3,
          "title": "子组件",
          "slug": "子组件-2"
        },
        {
          "level": 3,
          "title": "父组件",
          "slug": "父组件-2"
        },
        {
          "level": 2,
          "title": "八、v-model",
          "slug": "八、v-model"
        },
        {
          "level": 3,
          "title": "子组件",
          "slug": "子组件-3"
        },
        {
          "level": 3,
          "title": "父组件",
          "slug": "父组件-3"
        },
        {
          "level": 2,
          "title": "九、nextTick",
          "slug": "九、nexttick"
        },
        {
          "level": 2,
          "title": "十、ref子组件实例和defineExpose",
          "slug": "十、ref子组件实例和defineexpose"
        },
        {
          "level": 3,
          "title": "子组件",
          "slug": "子组件-4"
        },
        {
          "level": 3,
          "title": "父组件",
          "slug": "父组件-4"
        },
        {
          "level": 2,
          "title": "十、插槽slot",
          "slug": "十、插槽slot"
        },
        {
          "level": 3,
          "title": "子组件",
          "slug": "子组件-5"
        },
        {
          "level": 3,
          "title": "父组件",
          "slug": "父组件-5"
        },
        {
          "level": 2,
          "title": "十二、路由useRoute和useRouter",
          "slug": "十二、路由useroute和userouter"
        },
        {
          "level": 2,
          "title": "十三、路由导航守卫",
          "slug": "十三、路由导航守卫"
        },
        {
          "level": 2,
          "title": "十四、store",
          "slug": "十四、store"
        },
        {
          "level": 3,
          "title": "Vuex",
          "slug": "vuex"
        },
        {
          "level": 3,
          "title": "Pinia",
          "slug": "pinia"
        },
        {
          "level": 2,
          "title": "十五、生命周期",
          "slug": "十五、生命周期"
        },
        {
          "level": 2,
          "title": "十六、原型绑定与组件内使用",
          "slug": "十六、原型绑定与组件内使用"
        },
        {
          "level": 3,
          "title": "main.js",
          "slug": "main-js"
        },
        {
          "level": 3,
          "title": "组件内使用",
          "slug": "组件内使用"
        },
        {
          "level": 2,
          "title": "十七、v-bind() CSS变量注入",
          "slug": "十七、v-bind-css变量注入"
        },
        {
          "level": 2,
          "title": "十八、provide和inject",
          "slug": "十八、provide和inject"
        },
        {
          "level": 3,
          "title": "父组件",
          "slug": "父组件-6"
        },
        {
          "level": 3,
          "title": "子组件",
          "slug": "子组件-6"
        },
        {
          "level": 2,
          "title": "十九、对 await 的支持",
          "slug": "十九、对-await-的支持"
        },
        {
          "level": 2,
          "title": "二十、定义组件的name",
          "slug": "二十、定义组件的name"
        }
      ]
    }
  ],
  "themeConfig": {
    "subSidebar": "auto",
    "logo": "/image/logo.png",
    "authorAvatar": "/image/avatar.jpg",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "TypeScript",
        "link": "/TypeScript_docs/基础类型"
      },
      {
        "text": "Vue3",
        "link": "/Vue3_docs/Vue3.2"
      },
      {
        "text": "React",
        "link": ""
      },
      {
        "text": "Dart",
        "link": ""
      },
      {
        "text": "Flutter",
        "link": ""
      },
      {
        "text": "随心记录",
        "link": ""
      },
      {
        "text": "Github",
        "link": "https://github.com/huahaigo/LearningPark"
      }
    ],
    "sidebar": {
      "/TypeScript_docs/": [
        "基础类型",
        "接口",
        "类",
        "函数",
        "泛型"
      ],
      "/Vue3_docs/": [
        "Vue3.2",
        "Pinia"
      ]
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}